[tool.poetry]
name = "uvicore"
version = "0.1.0"
description = ""
authors = ["Matthew Reschke <mail@mreschke.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.57.0"
databases = "^0.3.2"
alembic = "^1.4.2"
uvicorn = "^0.11.5"
gunicorn = "^20.0.4"
typer = "^0.2.1"
click-help-colors = "^0.8"
prettyprinter = "^0.18.0"
environs = "^8.0.0"
jinja2 = "^2.11.2"
aiofiles = "^0.5.0"
colored = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pdoc3 = "^0.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
