[tool.poetry]
name = "uvicore"
version = "0.1.0"
description = ""
authors = ["Matthew Reschke <mail@mreschke.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.61.0"
databases = "^0.3.2"
alembic = "^1.4.2"
typer = "^0.3.2"
colored = "^1.4.2"
click-help-colors = "^0.8"
prettyprinter = "^0.18.0"
environs = "^8.0.0"
jinja2 = "^2.11.2"
aiofiles = "^0.5.0"
uvicorn = "^0.11.8"
gunicorn = "^20.0.4"
ipython = "^7.17.0"
asyncclick = "^7.0.9"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
mkdocs = "^1.1.2"
mkdocs-material = "^5.5.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
